apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-config
data:
  STORAGE_SYSTEM: cloud_spanner
  STORAGE_FLAG: --cloudspanner_uri=projects/PROJECT_ID/instances/trillian-spanner/databases/trillian-db
  SIGNER_DEQUEUE_BUCKET_FRACTION: "0.0078"
  SIGNER_BATCH_SIZE: "1800"
  SIGNER_INTERVAL: "2ms"
  SIGNER_NUM_SEQUENCERS: "10"
  SIGNER_MASTER_HOLD_JITTER: "7200s"
