apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: trillian-map
  name: trillian-map
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: trillian-map
    spec:
      containers:
      - command:
        - /go/bin/trillian_map_server
        - --mysql_uri=test:zaphod@tcp(db:3306)/test
        - --rpc_endpoint=0.0.0.0:8090
        - --http_endpoint=0.0.0.0:8091
        - --alsologtostderr
        image: us.gcr.io/project-name/map_server:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/metrics
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: trillian-map
        ports:
        - containerPort: 8090
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
status: {}
