apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: trillian-logsigner
  name: trillian-logsigner-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: trillian-log-signer
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: spanner-key
      containers:
      - command: ["/go/bin/trillian_log_signer",
        "$(STORAGE_FLAG)",
        "--storage_system=$(STORAGE_SYSTEM)",
        "--quota_system=noop",
        "--http_endpoint=0.0.0.0:8091",
        "--sequencer_guard_window=0s",
        "--sequencer_interval=500ms",
        "--num_sequencers=1",
        "--batch_size=2000",
        "--force_master=true",
        "--alsologtostderr"
        ]
        envFrom:
          - configMapRef:
              name: deploy-config
        image: gcr.io/$(CLOUD_PROJECT)/log_signer:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/metrics
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: trillian-logsigner
        ports:
        - containerPort: 8091
        resources: {}
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      restartPolicy: Always
status: {}
