apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: trillian-log
  name: trillian-logserver-deployment
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: trillian-log
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: trillian-key
      restartPolicy: Always
      containers:
      - name: trillian-logserver
        args: [
        "$(STORAGE_FLAG)",
        "--storage_system=$(STORAGE_SYSTEM)",
        "--quota_system=etcd",
        "--etcd_servers=trillian-etcd-cluster-client:2379",
        "--etcd_http_service=trillian-logserver-http",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--tracing",
        "--alsologtostderr"
        ]
        envFrom:
          - configMapRef:
              name: deploy-config
        image: gcr.io/${PROJECT_ID}/log_server:${IMAGE_TAG}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.4"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8091
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8090
          name: rpc
        - containerPort: 8091
          name: metrics
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.5.2
        ports:
          - name: profiler
            containerPort: 6060
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=logserver:http://localhost:8091/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --scrape-interval=5s
          - --export-interval=60s
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 20m
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
