apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  type: LoadBalancer
  # Make all connections from a particular client go to the same database
  # replica. This avoids a sequencer connecting to different replicas in
  # parallel and causing write conflicts that result in transaction rollbacks.
  sessionAffinity: ClientIP
  selector:
    app: galera
  # Only connections from 10.0.0.0/8 will be accepted.
  # To allow connections from elsewhere, replace 10.0.0.0/8 with the appropriate
  # CIDR IP range(s). To allow connections from any IP address, delete the
  # loadBalancerSourceRanges field.
  loadBalancerSourceRanges:
    - 10.0.0.0/8
---
apiVersion: v1
kind: Service
metadata:
  name: galera
  labels:
    app: galera
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    app: galera
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # These values must be base64 encoded.
  sst-username: c3N0
  sst-password: c3N0
  root-password: emFwaG9k
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: galera
spec:
  serviceName: galera
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: mysql-db
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
  template:
    metadata:
      labels:
        app: galera
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            limits:
              cpu: 2
          readinessProbe:
            exec:
              command: ["mysql", "-h", "127.0.0.1", "-u", "dummy", "-e", "SELECT 1"]
          image: us.gcr.io/trillian-test/galera:experimental
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          volumeMounts:
            - name: mysql-db
              mountPath: /var/lib/mysql
          env:
            - name: WSREP_SST_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-username
            - name: WSREP_SST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password

